import fs from 'fs-extra';
/**
 * Função que cria o arquivo de ponto de entrada da pasta modules.
 * Cria o index.ts que exporta os modulos referentes ao app.
 * @param dirDst 
 * @param modules 
 */
export function CreateModules(dirDst: string, modules: string[]) {
    console.log(`Write ${dirDst}/src/modules/index.ts`);
    const fileContent = `\
// AVISO: This file is auto-generated by wl-engine.
${modules.map((module: string) => `import ${module} from './${module}';`).join('\n')}

export default [${modules.join(', ')}];
`;
    fs.writeFileSync(`${dirDst}/src/modules/index.ts`, fileContent);
};