import fs from 'fs-extra';
import { ITask } from './interfaces/ITask';
/**
 * Classe responsável pot criar a váriavel que vai conter a baseUrl do app no diretórtio de destino.
 * @property {string} dirDst - Recebe uma string com o endereço que aponta para o diretório de destino.
 * @property {string} baseUrl - Recebe uma string com a URL do aplicativo alvo.
 * @method Execute - Cria a variável baseUrl no diretório de destino.
 */

export class CreateBaseUrl implements ITask {
    private readonly _dirDst: string;
    private readonly _baseUrl: string;

    constructor(dirSrc: string, dirDst: string) {
        this._dirDst = dirSrc;
        this._baseUrl = dirDst;
    }
    Execute(): void {
        console.log(`Write ${this._dirDst}/src/api/server.js`);
        const fileContent = `\
    // AVISO: This file is auto-generated by wl-engine.
    export const baseUrl = '${this._baseUrl}';
    `;
        fs.writeFileSync(`${this._dirDst}/src/baseUrl.js`, fileContent);
    }
}
