import fs from 'fs-extra';
import { ITask } from './interfaces/ITask';
/**
 * Função que cria o arquivo de ponto de entrada da pasta modules.
 * @description Cria o index.ts que exporta os modulos referentes ao app.
 * @property {string} dirDst - Recebe uma string com o endereço que aponta para o diretório de destino. 
 * @property {string} modules - Recebe um array de strings contendo o nome dos módulos.
 * @method Execute - Cria o arquivo index no diretório de destino.
*/
export class CreateModules implements ITask {
    private readonly _dirDst: string;
    private readonly _modules: string[];

    constructor(dirDst: string, modules: string[]) {
        this._dirDst = dirDst;
        this._modules = modules;
    }

    Execute(): void {
        console.log(`Write ${this._dirDst}/src/modules/index.ts`);
        const fileContent = `\
// AVISO: This file is auto-generated by wl-engine.
${this._modules.map((module: string) => `import ${module} from './${module}';`).join('\n')}

export default [${this._modules.join(', ')}];
`;
        fs.writeFileSync(`${this._dirDst}/src/modules/index.ts`, fileContent);
    }

}